/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDirectoryRouteImport } from './routes/app.directory'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppRecipesRouteImport } from './routes/app.recipes'
import { Route as AppSkinRouteImport } from './routes/app.skin'
import { Route as AppStoreRouteImport } from './routes/app.store'
import { Route as ApiPublicStoreSyncRouteImport } from './routes/api/public/store-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppSkinRoute = AppSkinRouteImport.update({
  id: '/skin',
  path: '/skin',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicStoreSyncRoute = ApiPublicStoreSyncRouteImport.update({
  id: '/api/public/store-sync',
  path: '/api/public/store-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/skin': typeof AppSkinRoute
  '/app/store': typeof AppStoreRoute
  '/app/': typeof AppIndexRoute
  '/api/public/store-sync': typeof ApiPublicStoreSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/skin': typeof AppSkinRoute
  '/app/store': typeof AppStoreRoute
  '/app': typeof AppIndexRoute
  '/api/public/store-sync': typeof ApiPublicStoreSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/skin': typeof AppSkinRoute
  '/app/store': typeof AppStoreRoute
  '/app/': typeof AppIndexRoute
  '/api/public/store-sync': typeof ApiPublicStoreSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/quiz'
    | '/app/recipes'
    | '/app/skin'
    | '/app/store'
    | '/app/'
    | '/api/public/store-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/quiz'
    | '/app/recipes'
    | '/app/skin'
    | '/app/store'
    | '/app'
    | '/api/public/store-sync'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/quiz'
    | '/app/recipes'
    | '/app/skin'
    | '/app/store'
    | '/app/'
    | '/api/public/store-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicStoreSyncRoute: typeof ApiPublicStoreSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/directory': {
      id: '/app/directory'
      path: '/directory'
      fullPath: '/app/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes': {
      id: '/app/recipes'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skin': {
      id: '/app/skin'
      path: '/skin'
      fullPath: '/app/skin'
      preLoaderRoute: typeof AppSkinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/store-sync': {
      id: '/api/public/store-sync'
      path: '/api/public/store-sync'
      fullPath: '/api/public/store-sync'
      preLoaderRoute: typeof ApiPublicStoreSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppQuizRoute: typeof AppQuizRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppSkinRoute: typeof AppSkinRoute
  AppStoreRoute: typeof AppStoreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDirectoryRoute: AppDirectoryRoute,
  AppQuizRoute: AppQuizRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppSkinRoute: AppSkinRoute,
  AppStoreRoute: AppStoreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicStoreSyncRoute: ApiPublicStoreSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
